export const Y_MAX = 600;
export const X_MAX = 800;
export const BUG_WIDTH = 60; // added 2 pixels for padding
export const BUG_HEIGHT = 60; // added 2 pixels for padding
export const FONT_FAMILY = "Monaco, Courier, monospace";
export const VELOCITY = 200;
export const VELOCITY_STEP = 50;
export const INITIAL_DELAY_BUGS = 3000;
export const INITIAL_DELAY_RECEIPTS = 2500;
export const DELAY_STEP_BUGS = 300;
export const DELAY_STEP_RECEIPTS = 270;
